
grammar    = piccolo ;
piccolo    = [{ fn | data, nl}], [fn | data, [nl]] ;
block      = "do", [{item, nl}], item, [nl], "end" ;
item       = assignment | expr ;
expr       = flow | block | access | fncall | construct | math | literal | name ;
assignment = name | namelist, "=", expr ;
name       = letter, { letter | digit | "_" } ;
fncall     = expr, "(", {expr, ","}, ")" ;
access     = expr, "." expr ;
fn         = "fn", name, "(", {name, ","}, ")", block ;
math       = unary, expr | expr, op, expr ;
unary      = "!" | "-" ;
op         = "*" | "+" | "/" | "-" | "%" | "&" | "|" ;
literal    = {digit} | bool | string | range ;
string     = "\"", {letter}, "\"" ;
range      = expr, "...", expr ;
bool       = "true" | "false" ;
flow       = if | while | for, block, ["else", block] ;
if         = "if", expr ;
while      = "while", expr ;
for        = "for", expr, "in", expr ;
construct  = "new", name, ["(", {assignment, ","}, ")"] ;
data       = "data", name, "is", attr, methods, "end" ;
attr       = {["pub"], assignment, nl} ;
methods    = {fn, nl} ;

