[alias]
r = ['run', '--example', 'main', '--']
c = ['check', '--all-targets']
b = ['build', '--all-targets']
rr = ['run', '--release', '--example', 'main', '--']
tt = ['run', '--example', 'test_files']
