[alias]
c = ['check', '--all-targets']
cc = ['hack', 'check', '--feature-powerset']

b = ['build', '--all-targets']
br = ['build', '--release', '--all-targets']
bb = ['hack', 'build', '--feature-powerset']
bbr = ['hack', 'build', '--release', '--feature-powerset']

r = ['use run or rr (or rl to enable logging)']
rl = ['run', '--features', 'log']
rr = ['run', '--release']

t = ['test', '--lib']
tt = ['run', '--bin', 'test_files']
ttt = ['hack', 'test', '--lib', '--feature-powerset']
