[alias]
c = ['check', '--all-targets', '--features', 'logging']
cc = ['hack', 'check', '--all-targets', '--feature-powerset', '--depth', '5']

b = ['build', '--all-targets']
bti = ['build', '--release']

r = ['use run or rr (or rl to get logging)']
rl = ['run', '--features', 'logging']
rr = ['run', '--release']

t = ['test', '--lib']
tt = ['run', '--release', '--bin', 'test_files']
ti = ['run', '--release', '--bin', 'interface_test']
ttt = ['hack', 'test', '--lib', '--feature-powerset', '--depth', '5']
