[alias]
c = ['check', '--all-targets']
cc = ['hack', 'check', '--all-targets', '--feature-powerset', '--depth', '5']

b = ['build', '--all-targets']
br = ['build', '--release', '--no-default-features', '--features', 'cli']

r = ['run', '--no-default-features', '--features', 'cli,color']
rl = ['run']
rr = ['run', '--release', '--no-default-features', '--features', 'cli,color']

t = ['test', '--lib']
tt = ['run', '--release', '--bin', 'test_files', '--no-default-features']
ti = ['run', '--release', '--bin', 'interface_test', '--no-default-features', '--features', 'cli']
ttt = ['hack', 'test', '--lib', '--feature-powerset', '--depth', '5']
